// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://alqwieqqrzzgsfftnlsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFscXdpZXFxcnp6Z3NmZnRubHN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMjIzMzgsImV4cCI6MjA1OTU5ODMzOH0.Vl_Dk3OAIglXgmknZoT9yw58qMtbsW2ZWk-ZIDPmTSA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);